### ISSUE TITLE
What is the reason for this?

### ISSUE THREAD

**Issue by github-lile** [andyzeng/visual-pushing-grasping#73]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from robot import Robot
  File "E:\AAAAAAAAAAAA\visual-pushing-grasping-master\robot.py", line 8, in <module>
    from simulation import vrep
  File "E:\AAAAAAAAAAAA\visual-pushing-grasping-master\simulation\vrep.py", line 59, in <module>
    c_GetJointPosition          = ct.CFUNCTYPE(ct.c_int32,ct.c_int32, ct.c_int32, ct.POINTER(ct.c_float), ct.c_int32)(("simxGetJointPosition", libsimx))
AttributeError: 'NoneType' object has no attribute '_handle'

**Comment by github-lile** [comment]
print:
_----------------------------------------------------
The remoteApi library could not be loaded. Make sure
it is located in the same folder as "vrep.py", or
appropriately adjust the file "vrep.py"
----------------------------------------------------_
But they locate in the same fiolder.

**Comment by MingshanHe** [comment]
I have solved this problem. I think the operating system you have used is `windows` and the python file in it needs a remote API file to run. So I recommend you copy the `remoteApi.dll` file to the `simulation` folder.

**Comment by Amina00Aslam** [comment]
> I have solved this problem. I think the operating system you have used is `windows` and the python file in it needs a remote API file to run. So I recommend you copy the `remoteApi.dll` file to the `simulation` folder.

Where can I get these two files which you mentioned? 
Thanks in advance :)

**Comment by MingshanHe** [comment]
These two files are contained in the location where the software `CoppeliaSim` is installed. Exactly, `CoppeliaSim/programming/remoteApiBindings/lib/lib/`. I can not guarantee the difference between the PC. 
Hope this will help you.

**Comment by yangliuxin-nn** [comment]
Hello, I found the remoteApi.dll file but did not find the simulation folder. Could you please help me whether the simulation folder is in the repository or somewhere else?

Many thanks for your time and help
